<a href="https://colab.research.google.com/github/SrihariniGJ/DeepLearning/blob/MP_Neuron/MPNeuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LOADING DATASET-BREAST CANCER**


In [0]:
import sklearn.datasets
import numpy as np


In [0]:
breast_cancer=sklearn.datasets.load_breast_cancer()


In [0]:
X=breast_cancer.data
Y=breast_cancer.target

In [7]:
print(X)
print(Y)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [8]:
print(X.shape,Y.shape)

(569, 30) (569,)


In [0]:
import pandas as pd


In [0]:
data = pd.DataFrame(breast_cancer.data,columns=breast_cancer.feature_names)

In [11]:
#@title
data.head()


mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [0]:
data['class']=breast_cancer.target

In [13]:
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [14]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [15]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [16]:
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

**TRAIN-TEST SPLIT**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X=data.drop('class',axis=1)
Y=data['class']

In [19]:
type(X)

pandas.core.frame.DataFrame

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [24]:
print(X.shape,X_train.shape,X_test.shape)

(569, 30) (512, 30) (57, 30)


In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

In [25]:
print(Y.shape,Y_train.shape,Y_test.shape)

(569,) (512,) (57,)


In [26]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

0.6274165202108963 0.63671875 0.543859649122807


In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y)

In [30]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [32]:
print(X_train.mean(),X_test.mean(),X.mean())

mean radius                 14.116703
mean texture                19.363828
mean perimeter              91.844277
mean area                  653.407227
mean smoothness              0.096252
mean compactness             0.103237
mean concavity               0.086608
mean concave points          0.048333
mean symmetry                0.180502
mean fractal dimension       0.062742
radius error                 0.407328
texture error                1.215211
perimeter error              2.878213
area error                  40.525188
smoothness error             0.007047
compactness error            0.025036
concavity error              0.030925
concave points error         0.011747
symmetry error               0.020485
fractal dimension error      0.003741
worst radius                16.275941
worst texture               25.747656
worst perimeter            107.147188
worst area                 881.221680
worst smoothness             0.132140
worst compactness            0.250311
worst concav

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1)

stratify---it divides train and test set in order to maintain their means(similar train and test means)

random_state---everytime we run the split statement the train and test split dataset varies. In order to avoid that(to get the same split everytime),we use random state which should be some constant






In [36]:
print(X_train.mean(),X_test.mean(),X.mean())

mean radius                 14.058656
mean texture                19.309668
mean perimeter              91.530488
mean area                  648.097266
mean smoothness              0.096568
mean compactness             0.105144
mean concavity               0.089342
mean concave points          0.048892
mean symmetry                0.181961
mean fractal dimension       0.062979
radius error                 0.403659
texture error                1.206856
perimeter error              2.861173
area error                  39.935506
smoothness error             0.007067
compactness error            0.025681
concavity error              0.032328
concave points error         0.011963
symmetry error               0.020584
fractal dimension error      0.003815
worst radius                16.194275
worst texture               25.644902
worst perimeter            106.757715
worst area                 871.647852
worst smoothness             0.132592
worst compactness            0.257415
worst concav